import {
  Home,
  Package,
  Building2,
  Users,
  BookOpen,
  Headphones,
  Lightbulb,
  Leaf,
  TrendingUp,
  Phone,
  Code,
  GraduationCap,
  Briefcase,
  Award,
  Globe,
  Heart,
  Target,
  Clock,
  FileText,
  Video,
  Download,
  BookMarked,
  MessageCircle,
  Mail,
  MessageSquare,
  HelpCircle,
  Shield,
} from "lucide-react";

export const menuData = {
  main: [
    {
      id: "home",
      title: "Home",
      subtitle: "Welcome to our comprehensive platform",
      icon: Home,
    },
    {
      id: "products",
      title: "Products & Services",
      subtitle: "Explore our comprehensive offerings",
      icon: Package,
      hasSubmenu: true,
      submenu: [
        {
          id: "technical",
          title: "Technical Consulting",
          subtitle: "Architecture and implementation guidance",
          icon: Code,
          hasSubmenu: true,
          submenu: [
            {
              id: "cloud",
              title: "Cloud Solutions",
              subtitle: "AWS, Azure, GCP expertise",
              icon: Globe,
            },
            {
              id: "security",
              title: "Security Audits",
              subtitle: "Comprehensive security assessment",
              icon: Shield,
            },
            {
              id: "devops",
              title: "DevOps Services",
              subtitle: "CI/CD and automation",
              icon: Code,
            },
          ],
        },
        {
          id: "business",
          title: "Business Strategy",
          subtitle: "Digital transformation and business planning",
          icon: TrendingUp,
        },
        {
          id: "training",
          title: "Training & Workshops",
          subtitle: "Team skill development and knowledge transfer",
          icon: GraduationCap,
          hasSubmenu: true,
          submenu: [
            {
              id: "react",
              title: "React Masterclass",
              subtitle: "Advanced React patterns",
              icon: Code,
            },
            {
              id: "node",
              title: "Node.js Workshop",
              subtitle: "Backend development",
              icon: Code,
            },
            {
              id: "design",
              title: "UI/UX Design",
              subtitle: "Modern design principles",
              icon: Lightbulb,
            },
          ],
        },
      ],
    },
    {
      id: "industry",
      title: "Industry Solutions",
      subtitle: "Hyper-vertical solutions for different industries",
      icon: Building2,
      hasSubmenu: true,
      submenu: [
        {
          id: "finance",
          title: "Financial Services",
          subtitle: "Banking and fintech solutions",
          icon: TrendingUp,
        },
        {
          id: "healthcare",
          title: "Healthcare",
          subtitle: "Digital health platforms",
          icon: Heart,
        },
        {
          id: "retail",
          title: "Retail & E-commerce",
          subtitle: "Online shopping experiences",
          icon: Package,
        },
        {
          id: "education",
          title: "Education",
          subtitle: "Learning management systems",
          icon: GraduationCap,
        },
      ],
    },
    {
      id: "company",
      title: "Company",
      subtitle: "Learn about our organization and culture",
      icon: Users,
      hasSubmenu: true,
      submenu: [
        {
          id: "about",
          title: "About Us",
          subtitle: "Our story, mission, and values",
          icon: Building2,
        },
        {
          id: "team",
          title: "Our Team",
          subtitle: "Meet the people behind our success",
          icon: Users,
        },
        {
          id: "careers",
          title: "Careers",
          subtitle: "Join our growing team",
          icon: Briefcase,
          hasSubmenu: true,
          submenu: [
            {
              id: "openings",
              title: "Open Positions",
              subtitle: "View current job openings",
              icon: Briefcase,
            },
            {
              id: "culture",
              title: "Company Culture",
              subtitle: "Life at our company",
              icon: Heart,
            },
            {
              id: "benefits",
              title: "Benefits & Perks",
              subtitle: "What we offer our team",
              icon: Award,
            },
          ],
        },
        {
          id: "leadership",
          title: "Leadership",
          subtitle: "Executive team and board of directors",
          icon: Award,
        },
        {
          id: "locations",
          title: "Office Locations",
          subtitle: "Find us around the world",
          icon: Globe,
        },
        {
          id: "values",
          title: "Our Values",
          subtitle: "Principles that guide us",
          icon: Target,
        },
        {
          id: "history",
          title: "Company History",
          subtitle: "Our journey and milestones",
          icon: Clock,
        },
      ],
    },
    {
      id: "resources",
      title: "Resources",
      subtitle: "Knowledge base, tools, and learning materials",
      icon: BookOpen,
      hasSubmenu: true,
      submenu: [
        {
          id: "blog",
          title: "Blog",
          subtitle: "Latest articles and insights",
          icon: FileText,
        },
        {
          id: "documentation",
          title: "Documentation",
          subtitle: "Technical guides and API docs",
          icon: BookMarked,
          hasSubmenu: true,
          submenu: [
            {
              id: "getting-started",
              title: "Getting Started",
              subtitle: "Quick start guides",
              icon: BookOpen,
            },
            {
              id: "api-reference",
              title: "API Reference",
              subtitle: "Complete API documentation",
              icon: Code,
            },
            {
              id: "tutorials",
              title: "Tutorials",
              subtitle: "Step-by-step tutorials",
              icon: GraduationCap,
            },
          ],
        },
        {
          id: "case-studies",
          title: "Case Studies",
          subtitle: "Success stories from our clients",
          icon: Award,
        },
        {
          id: "webinars",
          title: "Webinars",
          subtitle: "Live and recorded sessions",
          icon: Video,
        },
        {
          id: "whitepapers",
          title: "Whitepapers",
          subtitle: "In-depth research and reports",
          icon: FileText,
        },
        {
          id: "downloads",
          title: "Downloads",
          subtitle: "Tools, templates, and resources",
          icon: Download,
        },
        {
          id: "community",
          title: "Community Forum",
          subtitle: "Connect with other users",
          icon: MessageCircle,
        },
      ],
    },
    {
      id: "support",
      title: "Support",
      subtitle: "Get help and support when you need it",
      icon: Headphones,
      hasSubmenu: true,
      submenu: [
        {
          id: "help-center",
          title: "Help Center",
          subtitle: "FAQs and common solutions",
          icon: HelpCircle,
        },
        {
          id: "contact-support",
          title: "Contact Support",
          subtitle: "Get in touch with our team",
          icon: Mail,
          hasSubmenu: true,
          submenu: [
            {
              id: "email",
              title: "Email Support",
              subtitle: "support@company.com",
              icon: Mail,
            },
            {
              id: "live-chat",
              title: "Live Chat",
              subtitle: "Chat with us now",
              icon: MessageSquare,
            },
            {
              id: "phone",
              title: "Phone Support",
              subtitle: "1-800-SUPPORT",
              icon: Phone,
            },
          ],
        },
        {
          id: "ticket",
          title: "Submit a Ticket",
          subtitle: "Create a support request",
          icon: FileText,
        },
        {
          id: "status",
          title: "System Status",
          subtitle: "Check service availability",
          icon: TrendingUp,
        },
        {
          id: "training-support",
          title: "Training Resources",
          subtitle: "Learn how to use our products",
          icon: GraduationCap,
        },
        {
          id: "account",
          title: "Account Management",
          subtitle: "Billing and subscription help",
          icon: Users,
        },
      ],
    },
    {
      id: "research",
      title: "Research & Innovation",
      subtitle: "Cutting-edge research and innovation initiatives",
      icon: Lightbulb,
    },
    {
      id: "sustainability",
      title: "Sustainability",
      subtitle: "Environmental responsibility and sustainable technology",
      icon: Leaf,
    },
    {
      id: "investors",
      title: "Investor Relations",
      subtitle: "Financial information and investor resources",
      icon: TrendingUp,
    },
    {
      id: "contact",
      title: "Contact",
      subtitle: "Get in touch with our team",
      icon: Phone,
    },
  ],
};
